### ISSUE TITLE
Unhandled error for `invalid_grant`

### ISSUE THREAD

**Issue by lucasjohnston** [nicokaiser/passport-apple#23]
When replaying a Sign In With Apple request which has already been processed, a `TokenError` is thrown rather than an OAuth / Authorisation error, which results in a 500 Internal Server Error. I'm handling this externally for now, but a check should probably be introduced to check if the JSON error is due to an `invalid_grant` and responds accordingly 🙂 

```
TokenError: Internal Server Error
    at AppleStrategy.parseErrorResponse (/Users/lucas/src/.../node_modules/@nicokaiser/passport-apple/lib/strategy.js:198:20)
    at AppleStrategy._createOAuthError (/Users/lucas/src/.../node_modules/@nicokaiser/passport-apple/lib/strategy.js:228:26)
    at /Users/lucas/src/.../node_modules/@nicokaiser/passport-apple/lib/strategy.js:93:57
    at /Users/lucas/src/.../node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/Users/lucas/src/.../node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/Users/lucas/src/.../node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'invalid_grant',
  uri: undefined,
  status: 500,
  isBoom: true,
  isServer: true,
  data: null,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}
```

**Comment by nicokaiser** [comment]
What in your opinion would be a better error to be thrown in this case?

I adopted this behaviour from other OAuth based Passport strategies, it simply throws an error when something goes wrong while processing the authorization code received from Apple. This error can be caught by a subsequent error handler (e.g. in express).

As far as I understand the Passport interface, the results of the `authenticate` method can either be "success", "fail" (the user did not authenticate, this may result in an existing user being logged out) or "error". Replaying an authorization code must result in an error, since it is an error in the authorization flow. The application then must decide how to react (display an error page, log out the user, etc.).

**Comment by JoaquimLey** [comment]
(not the issue creator)
Shouldn't this be the standard behavior? 
By throwing the exception you as the library consumer can handle it unless I'm missing something.

**Comment by lucasjohnston** [comment]
i'm no longer using this package (switched to twitter oauth for product reasons) so can't remember the exact issue, but i believe the default behaviour is to emit a [`AuthorizationError`].(https://github.com/jaredhanson/passport/blob/9b9dbaa3eb3fc3b561812d95793e1ff6a355c3b8/lib/errors/authenticationerror.js)
iirc this results in a 4xx response to the client and is handled quietly by express/passport.

my case: if a user has a slow connection and it gets replayed, apple throws an `invalid_grant` error. `passport-apple` subsequently returns a `TokenError` which is unhandled by default, resulting in a backend exception and `500` client response.

tbh i'd argue it's a bad API design choice on apple's part to confuse `invalid_grant` configuration/server errors with what is probably a client error.
i'd suggest either checking the rejection and either handling this case within `strategy.js` or leaving a note in the docs for others 🙂
