### ISSUE TITLE
Add examples on how to use this with the Sign In with Apple button inside iOS

### ISSUE THREAD

**Issue by ablankenship10** [nicokaiser/passport-apple#5]
Apple's documentation for setting up the button in the app doesn't seem to explain how to connect it to your own API (via this package). An example on how to connect this package to an iOS app in Swift and/or React Native would be a great help!

**Comment by nicokaiser** [comment]
This package is for providing the feature to use "Sign in with Apple" to log in to a Node.js web application (which can run anywhere, in the browser on the desktop, on a mobile phone, or in an iOS Web View inside an application).

When used with iOS or macOS Safari, Apple uses their native logins, while when used on any other browser, a web based login form will be displayed by Apple.

This has nothing to do with iOS, Swift or React Native.

**Comment by ablankenship10** [comment]
Gotcha, so this only works with the webview login? We've implemented LinkedIn with another passport strategy that opens the linkedin signin form in a webview in the app and does the auth process that way. You're saying this is not meant to be used with a mobile app and a rest API? Sorry not trying to make this a support request, just really confused with how to implement this auth with apple stuff. We're getting a userId from the native Sign In with Apple button, but not sure where to go from there if this package is not for that, as all the other passport packages for apple seem to be unfinished or only built based on the initial spec released by Apple and not production code.

**Comment by nicokaiser** [comment]
@ablankenship10 This module works exactly like the LinkedIn Passport strategy, just, well, for Sign in with Apple.
If you implement it in your app with a WebView, you will need to run a backend service that handles the callback. You will get a User ID, and this is how you identify the user when they will come back, that's it. On the first login you may or may not get their name and email address, so often this is used to create a "local" user account with this information.

**Comment by bruun** [comment]
With my limited experience with oauth, here's a couple of problems I've identified using the module together with native iOS authentication. Please correct me if there something I've misunderstood!

1. Apple sends the authorization code and identity token to the app after authentication, so if the app then posts the authorization code to a web server running this package, the identity token fetched is not guaranteed to include the user information (email and name). In my quick testing, the email was included but not the name. A solution could be to extend the package to also accept the identity token from the client, verify it, and use the information embedded in it. Otherwise the developer must verify the identity token from the app using the Apple APIs directly, or by using a separate third party npm module. This module can still be used to obtain a refresh token, but that leads into problem 2:

2. The apps do not use the Service ID as the client id, but rather its Bundle ID. You therefore need to configure several instances of the passport package in order to support both web and native authentication.
