### ISSUE TITLE
Feature Token based authorization

### ISSUE THREAD

**Issue by renarsvilnis** [nicokaiser/passport-apple#9]
Hi, I'm trying to add apple sign-in support in our current app - we both support "direct" login via server and `access_token` token-based authorization used by ios/android apps for better UX.

Noticed that the strategy is missing `.userProfile(accessToken, cb)` method like in other established strategies such as facebook, google, ...
https://github.com/jaredhanson/passport-facebook/blob/master/lib/strategy.js#L137

Not very familiar with apple OAuth, is that a limitation of the API or just requires this strategy internal code refactoring to make that part public?

## Update

Got a bit familiar with the Apple sign-in docs, turns out you can only get the "user" profile the first time he logs in.

**Comment by nicokaiser** [comment]
This is because there is no user profile.

Long version:

The "user profile" in most OAuth 2 implementations is something that is retrieved with the Access Token. This works for Facebook, Google, etc.

Sign in with Apple however works a bit differently: there is no user profile (aka. `userinfo`) endpoint that can be called with an Access Token, but the user information is submitted by Apple (only) on the first successful login.

The Access Token (and also the Refresh Token) is pretty useless at the moment, the important information is in the ID Token: its `sub` property is a per-app identifier you can use to identify a user. That's all.

So, when using a "direct" login (I don't know how this works as I do not have much experience in iOS development), you may get an ID Token in its response, or it is not possible to retrieve user information later.
